import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { getMockCityLeaderboard } from '@/lib/demoMockData';

export interface CityLeaderboardEntry {
  municipalityId: string;
  name: string;
  totalPoints: number;
  isOwnCity: boolean;
}

/**
 * Reads the real city_leaderboard view (0010_city_leaderboard.sql) --
 * total points generated by each municipality's drivers, live off the
 * points_transactions ledger, same pattern as useLeaderboard.ts.
 */
export function useCityLeaderboard(limit = 10) {
  const { profile, isDemoAccount } = useAuth();
  const [entries, setEntries] = useState<CityLeaderboardEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (isDemoAccount) {
      setEntries(getMockCityLeaderboard());
      setLoading(false);
      setError(null);
      return;
    }

    let cancelled = false;
    setLoading(true);
    setError(null);

    const load = async () => {
      const { data, error: queryError } = await supabase
        .from('city_leaderboard')
        .select('municipality_id, municipality_name, total_points')
        .order('total_points', { ascending: false })
        .limit(limit);

      if (cancelled) return;
      if (queryError) {
        console.error('[useCityLeaderboard] failed to load city_leaderboard:', queryError);
        setError(queryError.message);
        setLoading(false);
        return;
      }

      setEntries(
        (data ?? []).map((row) => ({
          municipalityId: row.municipality_id,
          name: row.municipality_name,
          totalPoints: row.total_points,
          isOwnCity: row.municipality_id === profile?.municipality_id,
        }))
      );
      setLoading(false);
    };

    load();

    // A view can't be subscribed to directly -- any new points_transactions
    // row can shift city rankings, so re-run through it on any ledger change.
    const channel = supabase
      .channel('city-leaderboard')
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'points_transactions' }, () => load())
      .subscribe();

    return () => {
      cancelled = true;
      supabase.removeChannel(channel);
    };
  }, [limit, profile?.municipality_id, isDemoAccount]);

  return { entries, loading, error };
}
